In [1]:
import pandas as pd
import numpy as np

In [6]:
stocks_df = pd.read_csv('stocks.csv')
stocks_df.head(10)

         date   open   high    low  close    volume Name
0  2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1  2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2  2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3  2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4  2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL
5  2013-02-15  13.93  14.61  13.93  14.50  15628000  AAL
6  2013-02-19  14.33  14.56  14.08  14.26  11354400  AAL
7  2013-02-20  14.17  14.26  13.15  13.33  14725200  AAL
8  2013-02-21  13.62  13.95  12.90  13.37  11922100  AAL
9  2013-02-22  13.57  13.60  13.21  13.57   6071400  AAL

In [8]:
stocks_df = pd.read_csv('stocks.csv', usecols=['date', 'volume', 'Name'])
stocks_df.head()

         date    volume Name
0  2013-02-08   8407500  AAL
1  2013-02-11   8882000  AAL
2  2013-02-12   8126000  AAL
3  2013-02-13  10259500  AAL
4  2013-02-14  31879900  AAL

In [22]:
col_names = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Ticker Symbol']
stocks_df = pd.read_csv('stocks_no_header.csv', header=None, names=col_names)
stocks_df.head()

         Date   Open   High    Low  Close    Volume Ticker Symbol
0  2013-02-08  15.07  15.12  14.63  14.75   8407500           AAL
1  2013-02-11  14.89  15.01  14.26  14.46   8882000           AAL
2  2013-02-12  14.45  14.51  14.10  14.27   8126000           AAL
3  2013-02-13  14.30  14.94  14.25  14.66  10259500           AAL
4  2013-02-14  14.94  14.96  13.16  13.99  31879900           AAL

In [24]:
stocks_df = pd.read_csv('data/stocks.csv')
stocks_df.head()

         date   open   high    low  close    volume Name
0  2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1  2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2  2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3  2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4  2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL

In [27]:
stocks_df = pd.read_csv('stocks_semicolon.csv', sep=';')
stocks_df.head()

         date   open   high    low  close    volume Name
0  2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1  2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2  2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3  2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4  2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL

In [29]:
stocks_df = pd.read_csv('stocks.csv', index_col='date')
stocks_df.head()

             open   high    low  close    volume Name
date
2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL

In [34]:
stocks_df = pd.read_csv('stocks.csv')
stocks_df.dtypes

date       object
open      float64
high      float64
low       float64
close     float64
volume      int64
Name       object
dtype: object

In [36]:
types = {
    'open': np.float32,
    'high': np.float32,
    'low': np.float32,
    'close': np.float32,
    'volume': np.int32
}
stocks_df = pd.read_csv('stocks.csv', dtype=types)
stocks_df.dtypes

date       object
open      float32
high      float32
low       float32
close     float32
volume      int32
Name       object
dtype: object

In [38]:
stocks_df = pd.read_csv('stocks.csv', parse_dates=[0])
stocks_df.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
Name              object
dtype: object

In [41]:
stocks_df = pd.read_csv('stocks_missing_data.csv')
stocks_df.head()

/var/folders/gj/zph2y7c11j770xl_cf6rxs3w0000gn/T/ipykernel_99058/3710763722.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  stocks_df = pd.read_csv('stocks_missing_data.csv')

         date   open   high    low  close    volume Name
0  2013-02-08    NaN    NaN  14.63  14.75   8407500  AAL
1  2013-02-11  14.89    NaN  14.26  14.46   8882000  AAL
2  2013-02-12  14.45  14.51      ?  14.27   8126000  AAL
3  2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4  2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL

In [43]:
stocks_df = pd.read_csv('stocks_missing_data.csv', na_values=['?'])
stocks_df.head()

         date   open   high    low  close    volume Name
0  2013-02-08    NaN    NaN  14.63  14.75   8407500  AAL
1  2013-02-11  14.89    NaN  14.26  14.46   8882000  AAL
2  2013-02-12  14.45  14.51    NaN  14.27   8126000  AAL
3  2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4  2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL